---
abstract: 'Provide the cutadapt utility for eliminating polyA tails through pipx'
author:
  - 'Christos Argyropoulos <chrisarg@gmail.com>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  Alien::Build: '2.70'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-SeqAlignment-cutadapt
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Alien::SeqAlignment::cutadapt:
    file: lib/Alien/SeqAlignment/cutadapt.pm
    version: '0.01'
requires:
  Alien::Base: '0.038'
  parent: '0'
  strict: '0'
  warnings: '0'
version: '0.01'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.32'
  requires:
    share: {}
    system: {}
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
